import { z } from 'zod';

const objectId = z
  .string()
  .regex(/^[a-f\d]{24}$/, 'Must be a valid 24-char hex ObjectId');

// Base Transaction schema — derive API-specific schemas via .pick() / .omit()
export const BaseTransactionSchema = z.object({
  sourceAccountId: objectId.nullable(),

  destinationAccountId: objectId.nullable(),

  amount: z
    .number()
    .int('Amount must be an integer (paise)')
    .positive('Amount must be at least 1 paise'),

  type: z.enum(['TRANSFER', 'DEPOSIT', 'WITHDRAWAL'], {
    message: 'Type must be TRANSFER, DEPOSIT, or WITHDRAWAL',
  }),

  status: z.enum(['PENDING', 'PROCESSING', 'SETTLED', 'FAILED'], {
    message: 'Status must be PENDING, PROCESSING, SETTLED, or FAILED',
  }),

  // UUID v4 — generated by the client to prevent duplicate submissions
  idempotencyKey: z
    .string()
    .uuid('Idempotency key must be a valid UUID')
    .trim(),

  note: z
    .string()
    .max(255, 'Note must be 255 characters or fewer')
    .trim()
    .optional(),
});

export type BaseTransactionInput = z.infer<typeof BaseTransactionSchema>;
